### PR TITLE
Feature/build tree

### PR DESCRIPTION
**Pull request by rgtj2**
Add `build_tree` and `has_children?` to NestedLines

### CODE REVIEW

**Review by jhixson — DISMISSED** [review]
When I have a line representation like this:

```elixir
%NestedLines{
  lines: [
    [1],
    [0, 1],
    [0, 1],
    [0, 1],
    [0, 1],
    [0, 1],
    [1],
    [0, 1],
    [0, 1],
    [0, 1],
    [0, 1],
    [0, 1],
    [0, 0, 1]
  ]
}
```

The `build_tree` output gives me
```elixir
[
  %{
    line: "1",
    children: [
      %{line: "1.1", children: []},
      %{line: "1.2", children: []},
      %{line: "1.3", children: []},
      %{line: "1.4", children: []},
      %{line: "1.5", children: []}
    ]
  },
  %{
    line: "2",
    children: [
      %{line: "2.1", children: [%{line: "2.5.1", children: []}]},
      %{line: "2.2", children: []},
      %{line: "2.3", children: []},
      %{line: "2.4", children: []},
      %{line: "2.5", children: []}
    ]
  }
]
```

Should that child line be under this map instead? `%{line: "2.5", children: []}`

**Comment by rgtj2** [comment]
Adjusted logic for adding lines to the proper parent and added more tests.

**Comment by deepankar-j** [comment]
Looks awesome!  I like that the tree representation is explicit 👍.

🚀

**Review by deepankar-j — APPROVED** [review]
Ship it! 🚀 🌕

**Pull request merged**
